name: Bun CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: true
      VITEST: true
    strategy:
      matrix:
        bun-version: [latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: bun install
      - name: Verify environment and dependencies
        run: |
          echo "=== Environment Information ==="
          bun --version
          node --version
          echo "CI: $CI"
          echo "VITEST: $VITEST"
          echo ""
          echo "=== Dependency Verification ==="
          bun pm ls || echo "Dependency issues detected"
          echo ""
          echo "=== TypeScript Version ==="
          bunx tsc --version
          echo ""
      - run: bun run lint
      - run: bun run build --if-present
      - name: Run tests with memory monitoring
        run: |
          echo "Available memory before tests:"
          free -h
          bun run test:run
          echo "Available memory after tests:"
          free -h
      - name: Setup Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5
      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
